[workspace]
resolver = "3"
members = ["engine", "cli", "sdk", "sdk-macros"]
exclude = ["fixtures/test-plugin", "fixtures/sdk-sample"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Elastic-2.0"
authors = ["Wolfware LLC"]
repository = "https://github.com/wolfware-labs/moonlit"
rust-version = "1.97"

[workspace.dependencies]
wit-parser = "0.253"
wit-bindgen = "0.59.0"
saphyr-parser = "=0.0.11"
miette = "7.6"
thiserror = "2.0"
indexmap = "2.14"
dotenvy = "0.15"
regex = "1"
chrono = { version = "0.4", default-features = false, features = ["std"] }
rhai = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util", "process", "sync", "time", "signal"] }
tokio-util = { version = "0.7", features = ["rt"] }
oci-client = { version = "0.17", default-features = false, features = ["rustls-tls"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
sha2 = "0.11"
hex = "0.4"
dirs = "6"
base64 = "0.22"
wiremock = "0.6"
tempfile = "3"
wasmtime = { version = "46.0.1", features = ["component-model", "async"] }
wasmtime-wasi = "46.0.1"
wasmtime-wasi-http = "46.0.1"
wasmparser = "0.251"
anyhow = "1"
hyper = "1"
globset = "0.4"
clap = { version = "4", features = ["derive"] }
indicatif = "0.18"
comfy-table = "7"
console = "0.16"
serde_yaml_ng = "0.10"
humantime = "2"
assert_cmd = "2"
syn = "2"
quote = "1"
proc-macro2 = "1"
flate2 = "1"
