[workspace]
resolver = "3"
members = ["engine"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Elastic-2.0"
authors = ["Wolfware LLC"]
repository = "https://github.com/wolfware-labs/moonlit"
rust-version = "1.97"

[workspace.dependencies]
wit-parser = "0.253"
saphyr-parser = "=0.0.11"
miette = "7.6"
thiserror = "2.0"
indexmap = "2.14"
dotenvy = "0.15"
regex = "1"
chrono = { version = "0.4", default-features = false, features = ["std"] }
rhai = "1"
