name: "Nuget Package Release"

plugins:
  - name: "git"
    url: "file://D:/wolfware/moonlit/Wolfware.Moonlit/Wolfware.Moonlit.Plugins.Git/bin/Debug/net9.0/Wolfware.Moonlit.Plugins.Git.dll"
  - name: "gh"
    url: "file://D:/wolfware/moonlit/Wolfware.Moonlit/Wolfware.Moonlit.Plugins.GitHub/bin/Debug/net9.0/Wolfware.Moonlit.Plugins.Github.dll"
    config:
      token: $(GITHUB_TOKEN)
  - name: "sr"
    url: "file://D:/wolfware/moonlit/Wolfware.Moonlit/Wolfware.Moonlit.Plugins.SemanticRelease/bin/Debug/net9.0/Wolfware.Moonlit.Plugins.SemanticRelease.dll"
    config:
      openAi:
        apiKey: $(OPENAI_API_KEY)
  - name: "dotnet"
    url: "file://D:/wolfware/moonlit/Wolfware.Moonlit/Wolfware.Moonlit.Plugins.Dotnet/bin/Debug/net9.0/Wolfware.Moonlit.Plugins.Dotnet.dll"
    config:
      nugetSource: "https://nuget.pkg.github.com/wolfware-labs/index.json"
      nugetApiKey: $(GITHUB_TOKEN)


stages:
  analyze:
    - name: repo
      run: git.repo-context
    - name: tag
      run: gh.latest-tag
      config:
        prefix: "v"
    - name: items
      run: gh.items-since-commit
      config:
        sha: $(output:tag:commitSha)
    - name: conventionalCommits
      run: sr.analyze
      haltIf: output.conventionalCommits.CommitCount == 4
      config:
        commits: $(output:items:commits)
        includeScopes:
          - docs
    - name: version
      run: sr.calculate-version
      config:
        branch: $(output:repo:branch)
        baseVersion: $(output:tag:name)
        prereleaseMappings:
          dev: next

  build:
    - name: pack
      run: dotnet.pack
      config:
        project: "../../../Wolfware.Moonlit.Cli.csproj"
        version: $(output:version:nextFullVersion)
#    - name: publish
#      run: dotnet.push
#      config:
#        package: $(output:pack:packagePath)

  release:
    - name: changelog
      run: sr.generate-changelog
    - name: createRelease
      run: gh.create-release
      config:
        name: "Moonlit CLI Release $(output:version:nextVersion)"
        tag: "moonlit-cli-v$(output:version:nextVersion)"
        label: "released on @$(output:repo:branch)"
        changelog: $(output:changelog:categories)
        prerelease: $(output:version:isPrerelease)
        pullRequests: $(output:items:pullRequests)
        issues: $(output:items:issues)