name: Auto approve Bot PRs

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.CODE_OWNER_PAT }}
